version: "3.5"
services:

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      local_network:
        aliases:
          - postgres

  backend:
    container_name: backend-${APP_NAME}
    build:
      context: ./backend
      dockerfile: docker/dockerfile.local
    image: backend-${APP_NAME}:local
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./backend:/app/
    environment:
      APP_NAME: ${APP_NAME}
      BACKEND_ORIGIN: ${BACKEND_ORIGIN}
      CONNECTION: ${CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SCHEMA: ${DB_SCHEMA}
    depends_on:
      - db
    networks:
      local_network:
        aliases:
          - backend

  frontend:
    container_name: frontend-${APP_NAME}
    environment: 
      APP_NAME: ${APP_NAME}
    build:
      context: ./frontend
      dockerfile: docker/dockerfile.local
    image: frontend-${APP_NAME}:local
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app/
    networks:
      local_network:
        aliases:
          - frontend

networks:
  local_network:
    name: ${APP_NAME}-${INFR_NAME}-network

volumes:
  db-volume:
    name: db-${APP_NAME}